import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Box, Typography, Button } from '@mui/material'
import styled from '@emotion/styled'
import { Colors } from '../styles/colors'
import Flat from './flats'
import supabase from '../lib/suberbase'


export async function getStaticProps() {
  const { data: flats, error } = await supabase.from('flats').select('*')
  if (error) {
    throw new Error(error.message)
  }
  return {
    props: {
      flats: flats ?? [],
    },
  }
}

type Flat = {
  id: number
  created_at: string | null
  title: string | null
  is_published: boolean | null
  object_type: string | null
  additional_costs: number | null
  living_space: number | null
  city: string | null
  zip: number | null
  street: string | null
  street_number: number | null
}

export default function Home({ flats }: { flats: Flat[] }) {
  return (
    <>
      <Head>
        <title>Rate your Flat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ textAlign: 'center', fontSize: '54px' }}><h1>Welcome to Rate my Flat</h1> </Box>
      <Box sx={{ textAlign: 'center' }}>
        <h2>Spülmaschine kaputt? Club neben dran zu laut?</h2>
      </Box>
      <Box sx={{ textAlign: 'center' }}>
        <h3>{JSON.stringify(flats, null, 2)}</h3>
      </Box>
      <Box sx={{ display: 'flex', gap: 2, justifyContent: 'center', alignItems: 'center' }}>
        <Button style={{ backgroundColor: `${Colors.primary}` }} variant="contained">Registrieren</Button>
        <Button style={{ backgroundColor: `${Colors.secondary}` }} variant="outlined">Was genau ist das für ein Käse?</Button>
      </Box>

    </>
  )
}
